version: '3.8'

services:
  # Servicio de la API (tu app FastAPI)
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://sensor:secret@db:5432/sensorhub
    depends_on:
      db:
        condition: service_healthy
    # Sincronización en vivo para desarrollo
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: ./requirements.txt

  # Servicio de la Base de Datos (PostgreSQL)
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sensor
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sensorhub
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sensor -d sensorhub"]
      interval: 5s
      timeout: 5s
      retries: 5

# Volumen persistente para que tus datos no se borren al apagar el contenedor
volumes:
  pgdata: