"""esquema inicial: sensors y readings

Revision ID: 01a21f29f0c9
Revises: 
Create Date: 2026-08-06 14:14:09.919291

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '01a21f29f0c9'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensors')
    op.drop_index(op.f('ix_readings_id'), table_name='readings')
    op.drop_index(op.f('ix_readings_sensor_id'), table_name='readings')
    op.drop_table('readings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('readings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sensor_id', sa.VARCHAR(), nullable=False),
    sa.Column('value', sa.FLOAT(), nullable=False),
    sa.Column('unit', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readings_sensor_id'), 'readings', ['sensor_id'], 
                    unique=False)
    op.create_index(op.f('ix_readings_id'), 'readings', ['id'], unique=False)
    op.create_table('sensors',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('unit', sa.VARCHAR(), nullable=False),
    sa.Column('min_value', sa.FLOAT(), nullable=False),
    sa.Column('max_value', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
